name: update_readme
on:
  push:
  workflow_dispatch: 
  schedule:
    - cron: '0 0 * * *'

jobs: 
  update-readme: 
    name: update readme with wakatime
    runs-on: ubuntu-latest
    steps: 
      - uses: anmol098/waka-readme-stats@master
        with: 
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROFILE_VIEWS: "False"
          SHOW_EDITORS: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_SHORT_INFO: "False"