name: update_readme
on:
  push:
  workflow_dispatch: 
  schedule:
    - cron: '0 */8 * * *'

jobs: 
  # update-wakatime: 
  #   name: update readme with wakatime
  #   runs-on: ubuntu-latest
  #   steps: 
  #     - uses: anmol098/waka-readme-stats@master
  #       with: 
  #         WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
  #         GH_TOKEN: ${{ secrets.GH_TOKEN }}
  #         SHOW_PROFILE_VIEWS: "False"
  #         SHOW_EDITORS: "False"
  #         SHOW_LANGUAGE_PER_REPO: "False"
  #         SHOW_LOC_CHART: "False"
  #         SHOW_LINES_OF_CODE: "False"
  #         SHOW_SHORT_INFO: "False"
  #         SHOW_DAYS_OF_WEEK: "False"
  update-douban-blog:
    name: update douban and blog
    needs: update-wakatime
    runs-on: ubuntu-latest
    steps:
      - name: check repo
        uses: actions/checkout@v2
      - name: set up python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.8
      - name: configure pip
        uses: actions/cache@v2
        with: 
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: install python dependency
        run: |
          python -m pip install -r requirements.txt
      - name: pull before edit
        run: |
          git pull
      - name: update readme
        env: 
          GH_TOKEN: ${{ secrets.GH_TOKEN2 }}
        run: |-
          python build_readme.py
          cat README.md
      - name: commit and push if changed
        run: |-
          git diff
          git config --global user.email "typoverflow@outlook.com"
          git config --global user.name "typoverflow-bot"
          git add -A
          git commit -m "Bot: update readme automatically" || exit 0
          git push -f
